export const PERMISSIONS = {
  DASHBOARD_READ: 'dashboard:read',

  USERS_READ: 'users:read',
  USERS_WRITE: 'users:write',
  ROLES_READ: 'roles:read',
  ROLES_WRITE: 'roles:write',

  MFG_VENDORS_READ: 'mfg:vendors:read',
  MFG_VENDORS_WRITE: 'mfg:vendors:write',
  MFG_RAW_PURCHASE_READ: 'mfg:raw-purchase:read',
  MFG_RAW_PURCHASE_WRITE: 'mfg:raw-purchase:write',
  MFG_WIP_READ: 'mfg:wip:read',
  MFG_WIP_WRITE: 'mfg:wip:write',
  MFG_QUALITY_READ: 'mfg:quality:read',
  MFG_QUALITY_WRITE: 'mfg:quality:write',
  MFG_BRANDS_READ: 'mfg:brands:read',
  MFG_BRANDS_WRITE: 'mfg:brands:write',
  MFG_FINISHED_READ: 'mfg:finished:read',
  MFG_FINISHED_WRITE: 'mfg:finished:write',
  MFG_SALES_READ: 'mfg:sales:read',
  MFG_SALES_WRITE: 'mfg:sales:write',
  MFG_DAMAGES_READ: 'mfg:damages:read',
  MFG_DAMAGES_WRITE: 'mfg:damages:write',

  TRADING_ITEMS_READ: 'trading:items:read',
  TRADING_ITEMS_WRITE: 'trading:items:write',
  TRADING_VENDORS_READ: 'trading:vendors:read',
  TRADING_VENDORS_WRITE: 'trading:vendors:write',
  TRADING_PURCHASES_READ: 'trading:purchases:read',
  TRADING_PURCHASES_WRITE: 'trading:purchases:write',
  TRADING_SALES_READ: 'trading:sales:read',
  TRADING_SALES_WRITE: 'trading:sales:write',
  TRADING_DAMAGES_READ: 'trading:damages:read',
  TRADING_DAMAGES_WRITE: 'trading:damages:write',

  INVENTORY_READ: 'inventory:read',
  INVOICES_READ: 'invoices:read',
  INVOICES_WRITE: 'invoices:write',
  EXPENSES_READ: 'expenses:read',
  EXPENSES_WRITE: 'expenses:write',
  LEDGERS_READ: 'ledgers:read',
  REPORTS_READ: 'reports:read',
};

export const PERMISSION_GROUPS = [
  {
    label: 'General',
    items: [
      { key: PERMISSIONS.DASHBOARD_READ, label: 'View Dashboard' },
      { key: PERMISSIONS.REPORTS_READ, label: 'View Reports' },
      { key: PERMISSIONS.INVENTORY_READ, label: 'View Inventory' },
    ],
  },
  {
    label: 'User & Role Management',
    items: [
      { key: PERMISSIONS.USERS_READ, label: 'View Users' },
      { key: PERMISSIONS.USERS_WRITE, label: 'Manage Users' },
      { key: PERMISSIONS.ROLES_READ, label: 'View Roles' },
      { key: PERMISSIONS.ROLES_WRITE, label: 'Manage Roles' },
    ],
  },
  {
    label: 'Manufacturing',
    items: [
      { key: PERMISSIONS.MFG_VENDORS_READ, label: 'View Manufacturing Vendors' },
      { key: PERMISSIONS.MFG_VENDORS_WRITE, label: 'Manage Manufacturing Vendors' },
      { key: PERMISSIONS.MFG_RAW_PURCHASE_READ, label: 'View Raw Purchases' },
      { key: PERMISSIONS.MFG_RAW_PURCHASE_WRITE, label: 'Manage Raw Purchases' },
      { key: PERMISSIONS.MFG_WIP_READ, label: 'View Machine Entry (WIP)' },
      { key: PERMISSIONS.MFG_WIP_WRITE, label: 'Manage Machine Entry (WIP)' },
      { key: PERMISSIONS.MFG_QUALITY_READ, label: 'View Quality Output' },
      { key: PERMISSIONS.MFG_QUALITY_WRITE, label: 'Manage Quality Output' },
      { key: PERMISSIONS.MFG_BRANDS_READ, label: 'View Brands' },
      { key: PERMISSIONS.MFG_BRANDS_WRITE, label: 'Manage Brands' },
      { key: PERMISSIONS.MFG_FINISHED_READ, label: 'View Finished Production' },
      { key: PERMISSIONS.MFG_FINISHED_WRITE, label: 'Manage Finished Production' },
      { key: PERMISSIONS.MFG_SALES_READ, label: 'View Manufacturing Sales' },
      { key: PERMISSIONS.MFG_SALES_WRITE, label: 'Manage Manufacturing Sales' },
      { key: PERMISSIONS.MFG_DAMAGES_READ, label: 'View Manufacturing Damages' },
      { key: PERMISSIONS.MFG_DAMAGES_WRITE, label: 'Create / Edit / Delete Manufacturing Damages' },
    ],
  },
  {
    label: 'Trading',
    items: [
      { key: PERMISSIONS.TRADING_ITEMS_READ, label: 'View Trading Items' },
      { key: PERMISSIONS.TRADING_ITEMS_WRITE, label: 'Manage Trading Items' },
      { key: PERMISSIONS.TRADING_VENDORS_READ, label: 'View Trading Vendors' },
      { key: PERMISSIONS.TRADING_VENDORS_WRITE, label: 'Manage Trading Vendors' },
      { key: PERMISSIONS.TRADING_PURCHASES_READ, label: 'View Trading Purchases' },
      { key: PERMISSIONS.TRADING_PURCHASES_WRITE, label: 'Manage Trading Purchases' },
      { key: PERMISSIONS.TRADING_SALES_READ, label: 'View Trading Sales' },
      { key: PERMISSIONS.TRADING_SALES_WRITE, label: 'Manage Trading Sales' },
      { key: PERMISSIONS.TRADING_DAMAGES_READ, label: 'View Trading Damages' },
      { key: PERMISSIONS.TRADING_DAMAGES_WRITE, label: 'Create / Edit / Delete Trading Damages' },
    ],
  },
  {
    label: 'Accounting',
    items: [
      { key: PERMISSIONS.INVOICES_READ, label: 'View Invoices' },
      { key: PERMISSIONS.INVOICES_WRITE, label: 'Manage Invoices' },
      { key: PERMISSIONS.EXPENSES_READ, label: 'View Expenses' },
      { key: PERMISSIONS.EXPENSES_WRITE, label: 'Manage Expenses' },
      { key: PERMISSIONS.LEDGERS_READ, label: 'View Ledgers' },
    ],
  },
];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const DEFAULT_ROLES = [
  {
    name: 'Admin',
    slug: 'admin',
    description: 'Full access to all modules',
    isSystem: true,
    permissions: ALL_PERMISSIONS,
  },
  {
    name: 'Manager',
    slug: 'manager',
    description: 'Operations and accounting access',
    isSystem: true,
    permissions: ALL_PERMISSIONS.filter(
      (p) => !['users:write', 'roles:read', 'roles:write'].includes(p)
    ),
  },
  {
    name: 'Operator',
    slug: 'operator',
    description: 'Manufacturing and inventory operations',
    isSystem: true,
    permissions: [
      PERMISSIONS.DASHBOARD_READ,
      PERMISSIONS.MFG_VENDORS_READ,
      PERMISSIONS.MFG_RAW_PURCHASE_READ,
      PERMISSIONS.MFG_RAW_PURCHASE_WRITE,
      PERMISSIONS.MFG_WIP_READ,
      PERMISSIONS.MFG_WIP_WRITE,
      PERMISSIONS.MFG_QUALITY_READ,
      PERMISSIONS.MFG_QUALITY_WRITE,
      PERMISSIONS.MFG_BRANDS_READ,
      PERMISSIONS.MFG_BRANDS_WRITE,
      PERMISSIONS.MFG_FINISHED_READ,
      PERMISSIONS.MFG_FINISHED_WRITE,
      PERMISSIONS.MFG_SALES_READ,
      PERMISSIONS.MFG_DAMAGES_READ,
      PERMISSIONS.TRADING_ITEMS_READ,
      PERMISSIONS.TRADING_DAMAGES_READ,
      PERMISSIONS.TRADING_VENDORS_READ,
      PERMISSIONS.TRADING_PURCHASES_READ,
      PERMISSIONS.TRADING_SALES_READ,
      PERMISSIONS.INVENTORY_READ,
    ],
  },
];
